mmorpg/mmorpg/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poststable.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mmorpg/poststable/urls.py
from django.urls import path
from .views import (PostView, PopularList, subscribe, unsubscribe, CategoryList, PostDetail,
                    like, dislike, ResponsesList, user_comments, post_comments, author_posts, user_subs, CreatePost,
                    approve_comment, UpdatePost, DeletePost, SearchView, delete_response, comment_like,)

app_name = 'table'

urlpatterns = [
    path('', PostView.as_view(), name='posts'),
    path('<int:pk>', PostDetail.as_view(), name='post'),
    path('popular/', PopularList.as_view(), name='popular'),
    path('subscription/', user_subs, name='subscription'),
    path('create/', CreatePost.as_view(), name='create'),
    path('search/', SearchView.as_view(), name='search'),
    path('<int:pk>/edit', UpdatePost.as_view(), name='update'),
    path('<int:pk>/delete', DeletePost.as_view(), name='delete'),
    path('responses/', post_comments, name='responses'),
    path('comments/', user_comments, name='user_comments'),
    path('my_posts/', author_posts, name='author_post'),
    path('subscribe/<str:name>', subscribe, name='subscribe'),
    path('unsubscribe/<str:name>', unsubscribe, name='unsubscribe'),
    path('categories/<str:name>', CategoryList.as_view(), name='categories'),
    path('like/<int:pk>', like, name='like'),
    path('dislike/<int:pk>', dislike, name='dislike'),
    path('comment_like/<int:pk>', comment_like, name='comment_like'),
    path('approve/<int:pk>', approve_comment, name='approve'),
    path('delete/<int:pk>', delete_response, name='delete_response'),
]

mmorpg/poststable/models.py
from autoslug import AutoSlugField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from hitcount.models import HitCountMixin, HitCount
from django.utils.text import slugify
from django.contrib.contenttypes.fields import GenericRelation
from django.core.cache import cache

class Author(models.Model):
    userAuthor = models.OneToOneField(User, on_delete=models.CASCADE)
    userRating = models.SmallIntegerField(default=0)

    def update_rating(self):
        posts = self.post_set.all()
        comments = self.response_set.all()
        postRating = 0
        commentRating = 0

        if posts.exists():
            postValue = posts.aggregate(summ = Sum('postRating'))
            postRating += postValue.get('summ')

        if comments.exists():
            commentValue = comments.aggregate(summ=Sum('responseRating'))
            commentRating += commentValue.get('summ')

        self.userRating = postRating * 3 + commentRating
        self.save()

    def __str__(self):
        return f'User: {self.userAuthor}, {self.pk}'


class Category(models.Model):
    TANKS = 'Tanks'
    HEALERS = 'Healers'
    DD = 'DamageDealers'
    MERCHANTS = 'Merchants'
    GUILD_MASTERS = 'GuildMasters'
    QUEST_GIVERS = 'QuestGivers'
    BLACKSMITHS = 'BlackSmiths'
    TANNERS = 'Tanners'
    POTION_MAKERS = 'PotionMakers'
    SPELL_MASTERS = 'SpellMasters'
    CATEGORY_NAME_CHOICES = [
        (TANKS, 'Танки'),
        (HEALERS, 'Хилы'),
        (DD, 'ДД'),
        (MERCHANTS, 'Торговцы'),
        (GUILD_MASTERS, 'Гилдмастеры'),
        (QUEST_GIVERS, 'Квестгиверы'),
        (BLACKSMITHS, 'Кузнецы'),
        (TANNERS, 'Кожевники'),
        (POTION_MAKERS, 'Зельевары'),
        (SPELL_MASTERS, 'Мастера заклинаний'),
    ]
    name = models.CharField(max_length=15, choices=CATEGORY_NAME_CHOICES)
    subscribers = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'Категория: {self.name}'


class Response(models.Model):
    post_id = models.ForeignKey('Post', null=True, default=None, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    text = models.TextField(max_length=500)
    commentDate = models.DateTimeField(auto_now_add=True)
    comment_image = models.ImageField(upload_to='comment_images/%Y/%m/%d', null=True, default=None, blank=True)  #important!!
    approved = models.BooleanField(null=True, default=False)
    likedUser = models.ManyToManyField(User, blank=True)
    responseRating = models.SmallIntegerField(default=0, blank=True)


    @property
    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return f"{self.author.userAuthor.username}"

    @property
    def like(self):
        self.responseRating += 1
        self.save()
    @property
    def dislike(self):
        self.responseRating -= 1
        self.save()

    def get_absolute_url(self):
        return f'{self.id}'



class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    postDate = models.DateTimeField(auto_now_add=True)
    postUpdate = models.DateTimeField(auto_now=True)
    postCategory = models.ForeignKey(Category, blank=False, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=128)
    description = models.CharField(blank=True, max_length=300)
    preview_image = models.ImageField(upload_to='post_preview/%Y/%m/%d')
    text = RichTextUploadingField()
    postRating = models.SmallIntegerField(default=0)
    comments = models.ManyToManyField(Response, blank=True)
    likedUser = models.ManyToManyField(User, blank=True)
    slug = AutoSlugField(populate_from='title', default=None, null=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_p',
                                        related_query_name='hit_count_generic_relation')

    @property
    def like(self):
        self.postRating += 1
        self.save()
    @property
    def dislike(self):
        self.postRating -= 1
        self.save()

    def get_absolute_url(self):
        return f'/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')

    def __str__(self):
        return f"{self.author.userAuthor}, {self.title}"





mmorpg/templates/category_view.html
{% extends 'base/default.html' %}
{% load static %}
{% load hitcount_tags %}

{% block content %}
{% for post in categories %}
    <div class="col-12 mb-3 post border border-dark rounded-3 d-flex flex-column">
        <div class="container">
            <div class="row-auto d-flex pb-3">
                <a href="{% url 'table:categories' post.postCategory.name %}" class="btn btn-dark d-flex align-items-center">#{{ post.postCategory.name }}</a>
                <div class="col-auto">
                    <div class="d-flex align-items-center nav-text">{{ post.author.userAuthor}}</div>
                    <div class="d-flex align-items-center time-text">{{ post.postDate|date:'d.m.Y'}}</div>
                </div>
                <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                    {{ post.author.userRating }}
                </div>
                {% if user.is_authenticated %}
                    {% if subscriber %}
                        <form action="{% url 'table:unsubscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                            {% csrf_token %}
                            <input type='submit' class="btn btn-dark" value="Отписаться">
                        </form>
                    {% else %}
                          <form action="{% url 'table:subscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                            {% csrf_token %}
                            <input type='submit' class="btn btn-dark" value="Подписаться">
                          </form>
                    {% endif %}
                    {% include 'parts/nav_bar.html' %}
                {% else %}
                    <a href="{% url 'account_login' %}" class="ms-auto btn btn-dark">Подписаться</a>
                {% endif %}
            </div>
        <div class="row-auto d-flex pb-2">
            <a class="post-title link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.title }}</a>
        </div>
        {% if post.description %}
            <div class="row-auto d-flex">
                <a class="post-text link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.description }}</a>
            </div>
        {% endif %}
        </div>
        <img src="{{ post.preview_image.url }}" class="img-fluid" alt="">
        <div class="container">
            <div class="row-auto d-flex pt-3 pb-2" id="info_menu">
            {% if post.author.userAuthor != user %}
                {% if user in post.likedUser.all %}
                    <a class="btn btn-dark" href="{% url 'table:dislike' post.id %}">
                        <span class="bi bi-heart-fill" style="width: 10px"></span>
                        {{ post.postRating }}
                    </a>
                {% else %}
                    <a class="btn btn-dark d-flex flex-nowrap align-items-center" href="{% url 'table:like' post.id %}">
                       <span class="pe-1 bi bi-heart"></span>{{ post.postRating }}
                    </a>
                {% endif %}
            {% else %}
                <div class="d-flex pe-2 align-items-center nav-text">
                    <span class="bi bi-person-hearts" style="color: darkgray; width: 20px; font-size: 18px"></span>
                    {{ post.postRating }}
                </div>
            {% endif %}
                <div class="d-flex align-items-center nav-text">
                    <span class="pe-1 bi bi-chat-square-text"></span>
                    {{ post.comments.all|length }}
                </div>
                <div class="d-flex align-items-center nav-text ps-2">
                    <span class="bi bi-eye" style="color: darkgray; width: 21px; font-size: 18px"></span>
                    {% get_hit_count for post %}
                </div>
            </div>
        </div>
    </div>
{% empty %}
<div class="col-12 h-25 mb-3 post border border-dark rounded-3 d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="post-text d-flex justify-content-center align-self-center">
            Постов не найдено!
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

mmorpg/templates/popular.html
{% extends 'base/default.html' %}
{% load static %}
{% load hitcount_tags %}

{% block content %}
{% for post in popular %}
    <div class="col-12 mb-3 post border border-dark rounded-3 d-flex flex-column">
        <div class="container">
            <div class="row-auto d-flex pb-3">
                <a href="{% url 'table:categories' post.postCategory.name %}" class="btn btn-dark d-flex align-items-center">#{{ post.postCategory.name }}</a>
                <div class="col-auto">
                    <div class="d-flex align-items-center nav-text">{{ post.author.userAuthor}}</div>
                    <div class="d-flex align-items-center time-text">{{ post.postDate|date:'d.m.Y'}}</div>
                </div>
                <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                    {{ post.author.userRating }}
                </div>
                {% if user.is_authenticated %}
                    {% if subscriber %}
                        <form action="{% url 'table:unsubscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                            {% csrf_token %}
                            <input type='submit' class="btn btn-dark" value="Отписаться">
                        </form>
                    {% else %}
                          <form action="{% url 'table:subscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                            {% csrf_token %}
                            <input type='submit' class="btn btn-dark" value="Подписаться">
                          </form>
                    {% endif %}
                    {% include 'parts/nav_bar.html' %}
                {% else %}
                    <a href="{% url 'account_login' %}" class="ms-auto btn btn-dark">Подписаться</a>
                {% endif %}
            </div>
        <div class="row-auto d-flex pb-2">
            <a class="post-title link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.title }}</a>
        </div>
        {% if post.description %}
            <div class="row-auto d-flex">
                <a class="post-text link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.description }}</a>
            </div>
        {% endif %}
        </div>
        <img src="{{ post.preview_image.url }}" class="img-fluid" alt="">
        <div class="container">
            <div class="row-auto d-flex pt-3 pb-2" id="info_menu">
            {% if post.author.userAuthor != user %}
                {% if user in post.likedUser.all %}
                    <a class="btn btn-dark" href="{% url 'table:dislike' post.id %}">
                        <span class="bi bi-heart-fill" style="width: 10px"></span>
                        {{ post.postRating }}
                    </a>
                {% else %}
                    <a class="btn btn-dark d-flex flex-nowrap align-items-center" href="{% url 'table:like' post.id %}">
                       <span class="pe-1 bi bi-heart"></span>{{ post.postRating }}
                    </a>
                {% endif %}
            {% else %}
                <div class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-person-hearts" style="color: darkgray; width: 20px; font-size: 18px"></span>
                    {{ post.postRating }}
                </div>
            {% endif %}
                <div class="d-flex align-items-center nav-text">
                    <span class="pe-1 bi bi-chat-square-text"></span>
                    {{ post.comments.all|length }}
                </div>
                <div class="d-flex align-items-center nav-text ps-2">
                    <span class="bi bi-eye" style="color: darkgray; width: 21px; font-size: 18px"></span>
                    {% get_hit_count for post %}
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <div class="text-primary">
        Постов не найдено!
    </div>
{% endfor %}
{% endblock content %}

{% block scripts %}
    var css = '#popular { color: white; }';
    var style = document.createElement('style');
    if (style.styleSheet) {
        style.styleSheet.cssText = css;
    } else {
        style.appendChild(document.createTextNode(css));
    }
    document.getElementsByTagName('head')[0].appendChild(style);
{% endblock scripts %}

mmorpg/templates/post.html
{% extends 'base/default.html' %}
{% load static %}
{% load hitcount_tags %}

{% block content %}
<div class="col-12 post border border-dark rounded-3">
    <div class="container">
        <div class="row-auto d-flex pb-3">
            <a href="{% url 'table:categories' post.postCategory.name %}" class="btn btn-dark d-flex align-items-center">#{{ post.postCategory.name }}</a>
            <div class="col-auto">
                <div class="d-flex align-items-center nav-text">{{ post.author.userAuthor}}</div>
                <div class="d-flex align-items-center time-text">{{ post.postDate|date:'d.m.Y'}}</div>
            </div>
            <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                {{ post.author.userRating }}
            </div>
            {% if user.is_authenticated %}
                {% if subscriber %}
                    <form action="{% url 'table:unsubscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                        {% csrf_token %}
                        <input type='submit' class="btn btn-dark" value="Отписаться">
                    </form>
                {% else %}
                      <form action="{% url 'table:subscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                        {% csrf_token %}
                        <input type='submit' class="btn btn-dark" value="Подписаться">
                      </form>
                {% endif %}
                {% include 'parts/nav_bar.html' %}
            {% else %}
                <a href="{% url 'account_login' %}" class="ms-auto btn btn-dark">Подписаться</a>
            {% endif %}
        </div>
        <div class="row-auto d-flex pb-2">
            <a class="post-title link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.title }}</a>
        </div>
        {% if post.description %}
            <div class="row-auto d-flex">
                <a class="post-text link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.description }}</a>
            </div>
        {% endif %}
    </div>
    <img src="{{ post.preview_image.url }}" class="img-fluid" alt="">
    <div class="row-auto p-3">
        <p>{{ post.text|safe }}</p>
    </div>
    <div class="container">
        <div class="row-auto d-flex pt-3 pb-2" id="info_menu">
        {% if post.author.userAuthor != user %}
            {% if user in post.likedUser.all %}
                <a class="btn btn-dark" href="{% url 'table:dislike' post.id %}">
                    <span class="bi bi-heart-fill" style="width: 10px"></span>
                    {{ post.postRating }}
                </a>
            {% else %}
                <a class="btn btn-dark d-flex flex-nowrap align-items-center" href="{% url 'table:like' post.id %}">
                   <span class="pe-1 bi bi-heart"></span>{{ post.postRating }}
                </a>
            {% endif %}
        {% else %}
            <div class="d-flex pe-2 ps-2 align-items-center nav-text">
                <span class="bi bi-person-hearts" style="color: darkgray; width: 20px; font-size: 18px"></span>
                {{ post.postRating }}
            </div>
        {% endif %}
            <div class="d-flex pe-1 align-items-center nav-text">
                <span class="pe-1 bi bi-chat-square-text"></span>
                {{ post.comments.all|length }}
            </div>
            <div class="d-flex align-items-center nav-text">
                <span class="bi bi-eye" style="color: darkgray; width: 21px; font-size: 18px"></span>
                {% get_hit_count for post %}
            </div>
        </div>
    </div>
</div>

<div class="col-12 post border border-dark rounded-3 mt-4">
    <div class="container">
        <div class="post-text mt-2 mb-3">{{ post.comments.all|length }} Комментариев</div>
        {% if user.is_authenticated %}
            <form method="POST" action='' enctype="multipart/form-data">
        {% else %}
            <form method="" action='{% url 'account_login' %}'>
        {% endif %}
            {% csrf_token %}
            <div class="row-12 comment-area p-1 d-flex flex-wrap">
                {{ form.text }}
                <label for="id_comment_image">
                    <span class="bi bi-file-earmark-image ps-2 d-flex align-items-center" style="color: darkgray; font-size: 20px; opacity: 60%">
                        {{ form.comment_image }}
                    </span>
                </label>
                <input class="ms-auto btn btn-dark btn-sm" style="" type="submit">
            </div>
        </form>
        {% for comment in post.comments.all %}
            <div class="row-auto d-flex pb-2 mt-2">
                <div class="col-auto">
                    <div class="d-flex align-items-center nav-text">{{ comment.author.userAuthor }}</div>
                    <div class="ms-auto d-flex align-items-center time-text">{{ comment.commentDate|date:'d.m в m.i' }}</div>
                </div>
                <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                    {{ comment.author.userRating }}
                </div>
                <div class="row-auto ms-auto d-flex flex-nowrap">
                    {% if comment.approved %}
                        <span title="Одобрена автором" class="bi bi-bookmark-check-fill" style="width: 25px; font-size: 20px; opacity: 65%; color: #C9CCCD"></span>
                    {% endif %}
                    {% include 'parts/response_nav.html' %}
                </div>
            </div>
            <div class="row-auto ps-2 pt-2 d-flex">
                <p class="post-text">{{ comment.text }}</p>
            </div>
            {% if comment.comment_image %}
                <img src="{{ comment.comment_image.url }}" style="max-height: 400px; max-width: 70%;"  class="ps-2 img-fluid rounded-4" alt="">
            {% endif %}
            <div class="row-auto d-flex flex-wrap align-items-center">
            {% if user not in comment.likedUser.all and user != comment.author.userAuthor%}
                <a href="{% url 'table:comment_like' comment.id %}" class="nav-text d-flex link-underline-dark align-items-center">
                   <span class="bi bi-plus" style="color: darkgray; width: 17px; font-size: 20px"></span>{{ comment.responseRating }}
                </a>
            {% else %}
                <div class="nav-text d-flex link-underline-dark align-items-center">
                   <span class="bi bi-plus" style="color: darkgray; width: 17px; font-size: 20px"></span>{{ comment.responseRating }}
                </div>
            {% endif %}
            {% if not comment.approved and comment.author.userAuthor.id != request.user.id and post.author.userAuthor.id == request.user.id %}
                <a class="nav-text ms-auto" href="{% url 'table:approve' comment.id %}">Одобрить</a>
            {% endif %}
            </div>
        {% empty %}
            <div class="row-auto d-flex pb-3 justify-content-center mt-3">
                <div class="d-flex align-items-center nav-text">Пока нет комментариев</div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

mmorpg/templates/search.html
{% extends 'base/default.html' %}
{% load hitcount_tags %}

{% block content %}
{% for post in filter.qs %}
    <div class="col-12 mb-3 post border border-dark rounded-3 d-flex flex-column">
        <div class="container">
            <div class="row-auto d-flex pb-3">
                <a href="{% url 'table:categories' post.postCategory.name %}" class="btn btn-dark d-flex align-items-center">#{{ post.postCategory.name }}</a>
                <div class="col-auto">
                    <div class="d-flex align-items-center nav-text">{{ post.author.userAuthor}}</div>
                    <div class="d-flex align-items-center time-text">{{ post.postDate|date:'d.m.Y'}}</div>
                </div>
                <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                    {{ post.author.userRating }}
                </div>
                {% if subscriber %}
                    <form action="{% url 'table:unsubscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                        {% csrf_token %}
                        <input type='submit' class="btn btn-dark" value="Отписаться">
                    </form>
                {% else %}
                      <form action="{% url 'table:subscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                        {% csrf_token %}
                        <input type='submit' class="btn btn-dark" value="Подписаться">
                      </form>
                {% endif %}
            {% include 'parts/nav_bar.html' %}
            </div>
        <div class="row-auto d-flex pb-2">
            <a class="post-title link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.title }}</a>
        </div>
        {% if post.description %}
            <div class="row-auto d-flex">
                <a class="post-text link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.description }}</a>
            </div>
        {% endif %}
        </div>
        <img src="{{ post.preview_image.url }}" class="img-fluid" alt="">
        <div class="container">
            <div class="row-auto d-flex pt-3 pb-2" id="info_menu">
            {% if post.author.userAuthor != user %}
                {% if user in post.likedUser.all %}
                    <a class="btn btn-dark" href="{% url 'table:dislike' post.id %}">
                        <span class="bi bi-heart-fill" style="width: 10px"></span>
                        {{ post.postRating }}
                    </a>
                {% else %}
                    <a class="btn btn-dark d-flex flex-nowrap align-items-center" href="{% url 'table:like' post.id %}">
                       <span class="pe-1 bi bi-heart"></span>{{ post.postRating }}
                    </a>
                {% endif %}
            {% else %}
                <div class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-person-hearts" style="color: darkgray; width: 20px; font-size: 18px"></span>
                    {{ post.postRating }}
                </div>
            {% endif %}
                <div class="d-flex align-items-center nav-text">
                    <span class="pe-1 bi bi-chat-square-text"></span>
                    {{ post.comments.all|length }}
                </div>
                <div class="d-flex align-items-center nav-text ps-2">
                    <span class="bi bi-eye" style="color: darkgray; width: 21px; font-size: 18px"></span>
                    {% get_hit_count for post %}
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <div class="text-primary">
        Постов не найдено!
    </div>
{% endfor %}
{% endblock content %}

mmorpg/templates/user_subs.html
{% extends 'base/default.html' %}
{% load static %}
{% load hitcount_tags %}

{% block content %}
{% for post in user_subs %}
    <div class="col-12 mb-3 post border border-dark rounded-3 d-flex flex-column">
        <div class="container">
            <div class="row-auto d-flex pb-3">
                <a href="{% url 'table:categories' post.postCategory.name %}" class="btn btn-dark d-flex align-items-center">#{{ post.postCategory.name }}</a>
                <div class="col-auto">
                    <div class="d-flex align-items-center nav-text">{{ post.author.userAuthor}}</div>
                    <div class="d-flex align-items-center time-text">{{ post.postDate|date:'d.m.Y'}}</div>
                </div>
                <div title="Рейтинг пользователя" class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-stars" style="color: darkgray; width: 22px; font-size: 23px"></span>
                    {{ post.author.userRating }}
                </div>
                {% if subscriber %}
                    <form action="{% url 'table:unsubscribe' post.postCategory.name %}" class="ms-auto" method="Post">
                        {% csrf_token %}
                        <input type='submit' class="btn btn-dark" value="Отписаться">
                    </form>
                {% endif %}
            {% include 'parts/nav_bar.html' %}
            </div>
        <div class="row-auto d-flex pb-2">
            <a class="post-title link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.title }}</a>
        </div>
        {% if post.description %}
            <div class="row-auto d-flex">
                <a class="post-text link-opacity-25-hover link-underline-dark pb-3" href="{% url 'table:post' post.id %}">{{ post.description }}</a>
            </div>
        {% endif %}
        </div>
        <img src="{{ post.preview_image.url }}" class="img-fluid" alt="">
        <div class="container">
            <div class="row-auto d-flex pt-3 pb-2" id="info_menu">
            {% if post.author.userAuthor != user %}
                {% if user in post.likedUser.all %}
                    <a class="btn btn-dark" href="{% url 'table:dislike' post.id %}">
                        <span class="bi bi-heart-fill" style="width: 10px"></span>
                        {{ post.postRating }}
                    </a>
                {% else %}
                    <a class="btn btn-dark d-flex flex-nowrap align-items-center" href="{% url 'table:like' post.id %}">
                       <span class="pe-1 bi bi-heart"></span>{{ post.postRating }}
                    </a>
                {% endif %}
            {% else %}
                <div class="d-flex pe-2 ps-2 align-items-center nav-text">
                    <span class="bi bi-person-hearts" style="color: darkgray; width: 20px; font-size: 18px"></span>
                    {{ post.postRating }}
                </div>
            {% endif %}
                <div class="d-flex align-items-center nav-text">
                    <span class="pe-1 bi bi-chat-square-text"></span>
                    {{ post.comments.all|length }}
                </div>
                <div class="d-flex align-items-center nav-text ps-2">
                    <span class="bi bi-eye" style="color: darkgray; width: 21px; font-size: 18px"></span>
                    {% get_hit_count for post %}
                </div>
            </div>
        </div>
    </div>
{% empty %}
<div class="col-12 h-25 mb-3 post border border-dark rounded-3 d-flex flex-column justify-content-center align-items-center">
    <div class="container">
        <div class="post-text d-flex justify-content-center align-self-center">
            Постов не найдено!
        </div>
    </div>
</div>
{% endfor %}
{% endblock content %}

{% block scripts %}
    var css = '#subscribtion { color: white; }';
    var style = document.createElement('style');
    if (style.styleSheet) {
        style.styleSheet.cssText = css;
    } else {
        style.appendChild(document.createTextNode(css));
    }
    document.getElementsByTagName('head')[0].appendChild(style);
{% endblock scripts %}