mmorpg/mmorpg/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poststable.urls')),
    path('accounts/', include('allauth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mmorpg/poststable/urls.py
from django.urls import path
from .views import (PostView, PopularList, subscribe, unsubscribe, CategoryList, PostDetail,
                    like, dislike, ResponsesList, user_comments, post_comments, author_posts, user_subs, CreatePost,
                    approve_comment, UpdatePost, DeletePost, SearchView, delete_response, comment_like,)

app_name = 'table'

urlpatterns = [
    path('', PostView.as_view(), name='posts'),
    path('<int:pk>', PostDetail.as_view(), name='post'),
    path('popular/', PopularList.as_view(), name='popular'),
    path('subscription/', user_subs, name='subscription'),
    path('create/', CreatePost.as_view(), name='create'),
    path('search/', SearchView.as_view(), name='search'),
    path('<int:pk>/edit', UpdatePost.as_view(), name='update'),
    path('<int:pk>/delete', DeletePost.as_view(), name='delete'),
    path('responses/', post_comments, name='responses'),
    path('comments/', user_comments, name='user_comments'),
    path('my_posts/', author_posts, name='author_post'),
    path('subscribe/<str:name>', subscribe, name='subscribe'),
    path('unsubscribe/<str:name>', unsubscribe, name='unsubscribe'),
    path('categories/<str:name>', CategoryList.as_view(), name='categories'),
    path('like/<int:pk>', like, name='like'),
    path('dislike/<int:pk>', dislike, name='dislike'),
    path('comment_like/<int:pk>', comment_like, name='comment_like'),
    path('approve/<int:pk>', approve_comment, name='approve'),
    path('delete/<int:pk>', delete_response, name='delete_response'),
]

mmorpg/templates/parts/nav_bar.html
{% if post.author.userAuthor.id == request.user.id %}

<div class="dropdown">
    <a class="btn btn-sm btn-secondary rounded-circle dropdown-toggle" id="navDropdown1" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'table:update' post.id %}">Редактировать</a></li>
        <li><a class="dropdown-item" href="{% url 'table:delete' post.id %}">Удалить</a></li>
    </ul>
</div>

{% endif %}

mmorpg/templates/parts/paginator.html
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a style="text-decoration: none" href="?page=1">First&nbsp</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.paginator.num_pages }}">&nbsp</a>
        <a style="text-decoration: none" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif%}

mmorpg/templates/parts/response_nav.html
{% if comment.author.userAuthor.id == request.user.id %}

<div class="dropdown ms-auto">
    <a class="btn btn-sm btn-dark rounded-circle dropdown-toggle" id="navDropdown1" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"></a>
    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="{% url 'table:delete_response' comment.id %}">Удалить</a></li>
    </ul>
</div>

{% endif %}